# Generated by Django 3.0.6 on 2020-05-25 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('cell', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('e_waste_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Computer', 'Computer'), ('Phone', 'Phone'), ('Radio', 'Radio'), ('Charger', 'Charger'), ('Speaker', 'Speaker'), ('Printer', 'Printer'), ('Headphone', 'Headphone'), ('Cables', 'Cables')], max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
